version: '3.8'
services:
  backend:
    image: backend:0.1.0
    container_name: backend
    build:
      context: ./BackEnd
    ports:
      - "8080:8080"
    depends_on:
      - backend_database
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend_database:5432/publisher
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PathNotFind
      - keySetURI=http://security:9090/oauth2/jwks
  security:
    image: security:0.1.0
    container_name: security
    build:
      context: ./SecurityServer
    ports:
      - "9090:9090"
    depends_on:
      - security_database
    environment:
      - SERVER_PORT= 9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://security_database:5430/security
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PathNotFind
  backend_database:
    image: postgres:14.7-alpine
    container_name: backend_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PathNotFind
    ports:
      - "5432:5432"
    volumes:
      - ./.databases/backend_db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - backend_database_data:/var/lib/postgresql/data
    restart: unless-stopped
  security_database:
    image: postgres:14.7-alpine
    container_name: security_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PathNotFind
    expose:
      - "5430"
    ports:
      - "5430:5430"
    volumes:
      - ./.databases/security_db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - security_database_data:/var/lib/postgresql/data
    command: -p 5430
    restart: unless-stopped
volumes:
  backend_database_data:
  security_database_data: