spring.application.name=SecurityServer

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/security
spring.datasource.username=postgres
spring.datasource.password=PathNotFind
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.baselineOnMigrate = true

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/doc
springdoc.api-docs.path=/api-docs

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/oauth2/jwks